# Generated by Django 3.0.4 on 2020-05-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKnown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'DailyKnown',
                'verbose_name_plural': 'DailyKnowns',
            },
        ),
    ]
