# Generated by Django 3.0.6 on 2020-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('written', '0002_auto_20200524_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(max_length=1000),
        ),
    ]
